### ISSUE TITLE
Needs a README

### ISSUE THREAD

**Issue by waldyrious** [cmllr/ldc.js#7]
Would a PR proposing a readme along the lines of [distrochooser's](https://github.com/cmllr/distrochooser/blob/master/README.md) be considered?

**Comment by cmllr** [comment]
Thanks for the suggestion! As the result of our last conversation, I've merged this repository into cmllr/distrochooser.de. I will add and contributors guide tomorrow for further contributions, if wanted. 

I will deprecate this repository in favor of cmllr/distrochooser.
